### ISSUE TITLE
Deadlock when closing producer

### ISSUE THREAD

**Issue by gregspurrier** [mreiferson/TrendrrNSQClient#13]
I'm encountering deadlocks when calling NSQProducer's `close` method. Here is the report from the JVM thread dump:

````
Found one Java-level deadlock:
=============================
"New I/O worker #1":
  waiting to lock monitor 0x00007fbbbc103458 (object 0x00000007e0008980, a com.trendrr.nsq.Connections),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fbbbc1033a8 (object 0x00000007e0008948, a com.trendrr.nsq.NSQProducer),
  which is held by "New I/O worker #1"

Java stack information for the threads listed above:
===================================================
"New I/O worker #1":
        at com.trendrr.nsq.Connections.remove(Connections.java:95)
        - waiting to lock <0x00000007e0008980> (a com.trendrr.nsq.Connections)
        at com.trendrr.nsq.AbstractNSQClient._disconnected(AbstractNSQClient.java:213)
        - locked <0x00000007e0008948> (a com.trendrr.nsq.NSQProducer)
        at com.trendrr.nsq.Connection._disconnected(Connection.java:151)
        at com.trendrr.nsq.netty.NSQHandler.channelDisconnected(NSQHandler.java:50)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:570)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:365)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:555)
        at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
        at org.jboss.netty.channel.Channels$4.run(Channels.java:386)
        at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:367)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:291)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
"main":
        at com.trendrr.nsq.AbstractNSQClient._disconnected(AbstractNSQClient.java:212)
        - waiting to lock <0x00000007e0008948> (a com.trendrr.nsq.NSQProducer)
        at com.trendrr.nsq.Connection._disconnected(Connection.java:151)
        at com.trendrr.nsq.Connection.close(Connection.java:190)
        at com.trendrr.nsq.Connections.close(Connections.java:121)
        - locked <0x00000007e0008980> (a com.trendrr.nsq.Connections)
        at com.trendrr.nsq.AbstractNSQClient.close(AbstractNSQClient.java:218)
        at com.trendrr.nsq.NSQProducer.close(NSQProducer.java:230)
        at workbench.to_nsq$_main.doInvoke(to_nsq.clj:32)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at user$eval3.invoke(form-init1476674585784519325.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)

Found 1 deadlock.
````

A possible solution is to remove the call to `this._disconnected()` in `Connection.close()`. `_disconnected()` will be invoked later from the NIO worker thread by `NSQHandler.channelDisconnected()` when the socket closes. This breaks the deadlock for me, but I'm not sure whether this change will have any unintended consequences.

**Comment by mreiferson** [comment]
closed by #17
